name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and verify
        run: |
          docker build -t atp-api .
          docker run -d -p 5000:5000 --name test-api atp-api
          sleep 5
          curl --fail http://localhost:5000/health
          docker stop test-api
