name: CI/CD Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  alert-and-test:
    runs-on: ubuntu-latest
    steps:
      # Notificação no Discord
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          content: |
            🚀 **Evento no Repositório**
            - **Branch:** ${{ github.ref }}
            - **Autor:** ${{ github.actor }}
            - **Ação:** ${{ github.event_name }}
            - **Link:** https://github.com/${{ github.repository }}/commit/${{ github.sha }}

      # Instalação de dependências
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Execução dos testes
      - name: Run Unit Tests
        run: pytest --cov=app tests/ -v
        env:
          PYTHONPATH: ${{ github.workspace }}